version: '3.7'
services:
  web:
    build: ./front
    container_name: Frontend-Portifolio-Docker-Gabriel-Teixeira
    ports:
     - "8080:8080"
    volumes:
      - ./front:/usr/src/app
    command: bash -c 'yarn && yarn serve'