/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PersonalInfo: typeof import('./components/PersonalInfo.vue')['default']
    ProjectCarousel: typeof import('./components/ProjectCarousel.vue')['default']
    ProjectsRouter: typeof import('./components/ProjectsRouter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
