# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
      - name: Install Yarn
        shell: bash
        run: npm install yarn -g
      - name: Install Dependencies
        shell: bash
        run: cd front && yarn install
      - name: Install Dependencies
        shell: bash
        run: |
          cd front
          yarn install
      - name: Build
        shell: bash
        run: |
          yarn build
      - name: Move Built
        shell: bash
        run: mv ./dist ../
      - name: Compact Static Files
        shell: bash
        run: tar -czvf staticFolder.tar.gz ./dist
      - name: Upload to Github Repo
        uses: actions/upload-artifact@v2
        with:
          name: PortifolioPageArtifact
          path: staticFolder.tar.gz
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: served-page
          token: ${{secrets.PAT}}
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: PortifolioPageArtifact
      - name: Unpack Static Files
        shell: bash
        run: |
          shopt -s extglob
          rm -rf !(staticFolder.tar.gz)
          tar -xzf staticFolder.tar.gz
          cd dist
          mv * ../
          cd ..
          rmdir dist
          rm staticFolder.tar.gz
      - name: Set Commiter Name and Mail
        shell: bash
        run: |
          git config --global user.email "clownDeployer@wildclown.com"
          git config --global user.name "Clown Deployer"
      - name: Commit page file changes to branch
        shell: bash
        run: |
          git add .
          git commit -m "Uploading page, GLHF"
          git push
